### ISSUE TITLE
code completion TODO

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-code#932]
- [x] fix offline usage - we are currently fetching pyodide from the pyodide cdn. webpack has issues with the current pyodide package. these need to get sorted.
- [x] install a specific version of `pybricks-jedi` package - this is needed if we make breaking changes to the Python package during development so we don't break regular users
- [ ] sort order - it would be nice to have at least some basic sorting, like list items from `__main__` first then items from pybricks modules, then everything else
- [ ] fix active signature/prameter - should not be hard-coded to 0 - https://github.com/pybricks/pybricks-api/blob/a758eaa1db5969a0c64232ecad2c5523acb1acd7/jedi/src/pybricks_jedi/__init__.py#L320-L321
- [x] parameter docs - the editor can show per-parameter docs but jedi doesn't know how to parse these - we would have to make our own parser
- [ ] additional features? - monaco and jedi have many features we aren't using - we can probably live without most of them - showing docs on hover might be a nice addition though
- [x] update to Pyodide 0.21 - this includes a fix to avoid spamming the browser console with warning messages when python code is interrupted
- [ ] disable on mobile - monaco editor officially does not support mobile devices and this is unusable on mobile because it doesn't fit on the screen
- [ ] Insert `()` for functions - it is a common beginner mistake to use function getters like properties.

**Comment by laurensvalk** [comment]
> fix active signature/prameter

> parameter docs -

Is that related to the following, or are these separate issues?

![image](https://user-images.githubusercontent.com/12326241/175763164-f242e99c-785d-4652-bb43-3e07a6df8689.png)

**Comment by dlech** [comment]
It looks like there is a `raw=True` option we need to enable. https://jedi.readthedocs.io/en/latest/docs/api-classes.html#jedi.api.classes.BaseName.docstring

**Comment by laurensvalk** [comment]
Nice, seems like that would take care of the first one.

And we can strip off any leading lines that start with the function/method/class name of the signature we're dealing with. That should take care of the second one or more if there are overloads.

**Comment by laurensvalk** [comment]
Instead of reflowing body text, we could make the text box match the 79(?) character width. Then arguments will look correct too. And there will be less folding of the technical signature at the top.

**Comment by dlech** [comment]
The unfinished items here are nice to have but not essential. So closing this issue as done and we can open new issues for individual features if we still think they are needed.
